### ISSUE TITLE
Server config file

### ISSUE THREAD

**Issue by jeremyrsmith** [polynote/polynote#10]
We need some server configuration, which should go in a (preferably YAML) file. This would contain server-specific configuration (port, notebook path(s), etc) as well as default notebook config for new notebooks.

**Comment by indig** [comment]
Curious as to why you prefer YAML to something like https://github.com/lightbend/config

Is it just that you feel YAML is a bit more accessible or are there other reasons? 

My main concern with YAML is just that right now I'm seeing lots of user errors due to indentation and other bugs in a project which has a yaml config (though to be fair, our config would likely be a lot simpler than the one in that project).

**Comment by jeremyrsmith** [comment]
Fixed by #74
