### ISSUE TITLE
more options for polynote.py run

### ISSUE THREAD

**Issue by antonkulaga** [polynote/polynote#1160]
I would like:
1) To be able to turn non-error spark logging off as it is too verbose and often useless
2) give custom parameters (maybe with yaml file) to the notebooks. Similar to how papermill does is https://papermill.readthedocs.io/en/latest/usage-parameterize.html#

**Comment by jonathanindig** [comment]
Hi @antonkulaga, we already have an issue open regarding the programmatic execution of notebooks: https://github.com/polynote/polynote/issues/1052

Regarding Spark logging, if you know of a reliable way to turn off Spark logging programmatically I'm sure we'd be all ears. Unfortunately as far as I am aware the best way to set Spark logging is [to provide your own `log4j.properties` file](https://spark.apache.org/docs/latest/configuration.html#configuring-logging), which you can do today with Polynote (using the new JVM args options). Maybe that would fit your needs? 

Let us know if you find a better way to set Spark logging programmatically in a way that would work for everyone and we'd be happy to take a look at at. Or better yet, feel free to contribute a PR! [Here's a good place to start](https://github.com/polynote/polynote/blob/master/polynote-spark/src/main/scala/polynote/kernel/interpreter/scal/ScalaSparkInterpreter.scala#L25). Or if the `log4j.properties` route works for you, please do contribute that file back so that others can use it as well. Thanks!
