### ISSUE TITLE
Inject cell containing template code when creating new notebook

### ISSUE THREAD

**Issue by shangqing-li** [polynote/polynote#1190]
We'd like to onboard our Polynote users with a default template (one Scala cell would be sufficient) each time they create a new notebook. There is nbextension for Jupyter notebooks called [jupytertemplate](https://github.com/xtreamsrl/jupytemplate), and I am wondering if there is any similar approach to develop such extensions in Polynote. Or alternatively, is there any workaround that can automatically fill in one cell with Scala template after creating new notebook?

I have seen [this open issue](https://github.com/polynote/polynote/issues/243) and wonder if this could be the solution if it is available in the future.

**Comment by jonathanindig** [comment]
HI @shangqing-li, it sounds like #243 is exactly what you're asking about! 

We don't have that feature yet, but one workaround might be just having a template `.ipynb` file that your users can [import](https://polynote.org/polynote/0.4.1/docs/notebooks-list.html#importing-a-notebook) when they need to create a new notebook (rather than creating a blank one). 

I know this isn't an ideal solution, but it might help tide you over until we implement a proper predef. 

Out of curiosity, what sort of code would you want to put in the template?

**Comment by jeremyrsmith** [comment]
I'm not sure this is about predef (which is code you can't see or edit). More about just changing the default content of a new notebook.

The content of a new notebook is rather unfortunately hardcoded. There's no good reason it _has_ to be that way – maybe we should pull out the "template notebook" into a file that people can edit if they want.

**Comment by shangqing-li** [comment]
Thanks @jonathanindig and @jeremyrsmith for the response!

> We don't have that feature yet, but one workaround might be just having a template .ipynb file that your users can import when they need to create a new notebook (rather than creating a blank one).

Thanks for the suggestion! We are already allowing our users clone from one template notebook, but the user feedback is that it would be more helpful if this copy/clone/import step can be removed.

> Out of curiosity, what sort of code would you want to put in the template?

We want to pre-populate code template in Scala, and this template defines interfaces on how users read/write data through Spark session. 

> maybe we should pull out the "template notebook" into a file that people can edit if they want.

@jeremyrsmith if there is a way to have "template notebook" customizable, our problem is solved easily. Would love to know if this is doable from Polynote's design.

**Comment by jeremyrsmith** [comment]
@shangqing-li this isn't something you can do today, but I don't think it's a design issue.

Here's the (de-facto) place where all "new" notebooks get created: https://github.com/polynote/polynote/blob/master/polynote-server/src/main/scala/polynote/server/repository/FileBasedRepository.scala#L322

It wouldn't be so hard to try loading from some kind of "blessed" template notebook file first. Want to give it a try?

**Comment by jeremyrsmith** [comment]
Alternatively, we could add an optional item to the config that lets you specify the default cells of a new notebook, rather than having it be hard coded. I'm ambivalent as to which is better (cells from config, or some kind of "template.ipynb" file). @jonathanindig?

**Comment by jonathanindig** [comment]
I guess the word "predef" is overloaded - in #243 I was always intending "predef" to mean "a predefined first cell (that users can see/edit)". But I can see how that can conflict with the current internal "predef", which is hidden (and rightly so). 

The way I pictured it was indeed putting it in the config, something like: 
```
behavior: # anywhere else? 
  predef:  # can call it template or something else if that's ambiguous?
   lang: scala  # or python, etc
   code: |
     import com.mycompany.CommonlyImportedClass
     // other stuff....
```

Doing it in the config seems consistent with the other settings we have: default spark settings, deps, repos, etc. 

OTOH, (just thinking aloud here) it might be more convenient to just specify a template ipynb file, because it could have the entire configuration at once since you'd want to make sure you add the dep on `com.mycompany:common-stuff:version`, the `http://com.mycompany/maven-repo` resolver... etc. before you can import `CommonlyImportedClass`.

I wonder if it makes sense to support template "bundles" (similar to the spark templates we have today). Users would create a new notebook and there could be a little drop-down selecting which bundle (or even a wizard specifying certain configs...). For example, I could see a few templates: `Empty`, `Spark Notebook` (then, later, pick a version), `Python Notebook`, `Tensorflow Notebook`, `Scala 3 Notebook (no Spark)`, `CommonlyImportedClass Notebook` ... etc. 

Maybe we start with specifying it in the config while we think a little more about the other stuff?

**Comment by jeremyrsmith** [comment]
I mean, there's no real reason that the default empty notebook should be a text cell that says "Start editing!". Why shouldn't you be able to edit that, is my reasoning. It makes good sense and would be a pretty straightforward way to resolve the issue.

**Comment by jonathanindig** [comment]
@jeremyrsmith I agree! Like I said, I think the most straightforward way to handle this would be to allow users to specify the contents of the first cell in the config. My example put it under `behavior` but a different key would be fine, too. 

(In the future, we may want to revisit the idea of "templates" to provide a richer experience but that would require more design work, as I mentioned)

**Comment by shangqing-li** [comment]
@jeremyrsmith Based on the thread seems that the current suggestion is to make first cell code (a.k.a. template) customizable in the `config.yml` file? If this is not prioritized from your team, I'd like to give it a try here.

**Comment by jeremyrsmith** [comment]
@shangqing-li yes, I think one good place to start would be to have an (optional) configuration item (say, under `behavior`) called e.g. "default_notebook", which if present, defines a path to a notebook file to use as the content of a new Notebook. If the setting doesn't exist, it would fall back to the current behavior. If the setting does exist, but the pointed file doesn't exist, it would log an error and then fall back to the current behavior.

If you want to give that a try, I'm available to help! Feel free to chat about it in polynote/polynote on gitter, or DM me on gitter if you like!

**Comment by shangqing-li** [comment]
Sounds great! Will give this a try, thanks @jeremyrsmith for providing the guidance!

**Comment by shangqing-li** [comment]
@jeremyrsmith @jonathanindig Just raised a PR for what we discussed above.
