### ISSUE TITLE
Unable to reasign a var

### ISSUE THREAD

**Issue by raproth** [polynote/polynote#1199]
**Description**
It sseems that polynote is not able to change a reference of a var, i.e. change the reference to another object:

![image](https://user-images.githubusercontent.com/20788208/131974149-b040dd3c-3cb0-4da6-9456-4498c181861c.png)

**Reproduction**
1. define a cell with a var, e.g. var a = "a"
2. in the next cell, try to change the referenece this var, e.g. a="b"

**Environment**
Release 0.42

**Comment by jeremyrsmith** [comment]
Hi @raproth,

Please don't use a `var` across notebook cells. There is almost never a good reason to do so. A `var` is fine to use locally, when it's necessary to efficiently compute something. But sharing it across cells would go against the purpose of Polynote, which is to make cells run as deterministically as possible.

I think we're probably not going to fix this. If you really want to use a var, you can nest it in an `object` or something – not that you _should_, but Polynote can't realistically stop you in that case.

You might also consider [almond](https://github.com/almond-sh/almond), which is a Jupyter kernel for Scala. Since it's REPL-based, it's not as principled about cell ordering and mutability, so it probably will work the way you want.
