### ISSUE TITLE
ipynb compatibility for ipython notebook repo

### ISSUE THREAD

**Issue by indig** [polynote/polynote#13]
1. Currently when I try to open a Polynote notebook in Jupyter I get ```Unreadable Notebook: /Users/jindig/projects/polynote/notebooks/test notebook.ipynb AttributeError('metadata')```

2. Going forward we may want to have some tests that verify our compliance with the standard if that's our goal (how strict is that goal?)

**Comment by indig** [comment]
Also, are we interested in the other way round (reading ipynbs generated by jupyter) or do we just want to make sure that our files output proper ipynbs

**Comment by jeremyrsmith** [comment]
I think @aishfention mentioned that if each cell has a metadata (even if it's empty) then other ipynb-based tools are happier to read it. We can't make it non-optional (because we don't want to enforce that it's there when we read the notebook) but we can make sure it's present whenever notebook is written.

**Comment by jeremyrsmith** [comment]
I think it would be great to be able to read foreign ipynb files. It tries to do this already, but I haven't tested to what extent it works. Magics will kind of break it right now, I expect, but I'd hope to make that smarter / more compatible.
