### ISSUE TITLE
Request: Ability to mount Polynote in a subpath

### ISSUE THREAD

**Issue by rabejens** [polynote/polynote#1364]
I am running a Zero to Jupyterhub installation where each user is assigned the path "/user/username". The proxy expects this routing to be done in the single user pod, i.e., the single user pod must serve its UI at /user/username.

Currently, Polynote serves everything at / and configuration option `ui / base_uri` only updates the `<base>` tag.

It would be nice if there was an option to also specify the sub path to serve Polynote from.

**Comment by omidmogasemi** [comment]
Hi @rabejens! I _think_ the `base_uri` setting should allow you to serve Polynote's front-end from a specific sub path. I'm not sure exactly what you mean by `base pod`, but are you looking to actually run Polynote's server from a sub-path on a port?

**Comment by rabejens** [comment]
No, it serves it from the root but only adds a `<base>` tag.

I now worked around this by adding a nginx container into the pod that functions as a reverse proxy and redirects the requests accordingly.

**Comment by jeremyrsmith** [comment]
@rabejens The `<base>` configuration is intended for use with a reverse proxy to "mount" polynote at a particular subpath, so I think you found the right solution. But out of curiosity, what were you picturing when you opened the issue? The polynote server would serve from a subpath and 404 everything outside of that subpath? Is this a quirk of Zero to Jupyterhub? I'd expect that whatever reverse proxy it's using could directly "mount" polynote at a subpath, rather than needing a second reverse proxy just to handle the path mangling.
