### ISSUE TITLE
Hotkey to run all cells

### ISSUE THREAD

**Issue by jonathanindig** [polynote/polynote#266]

**Comment by kuckjwi0928** [comment]
@jonathanindig 
Can I improve this issue?

**Comment by jonathanindig** [comment]
@kuckjwi0928 of course!

**Comment by kuckjwi0928** [comment]
@jonathanindig 
Can we use the hot key Ctrl+Shift+Enter?

**Comment by jonathanindig** [comment]
We actually already use this hotkey: 
```
Shift+Cmd+Enter | "Run this cell and insert a new cell below it."
```

See for example: https://github.com/polynote/polynote/blob/master/polynote-frontend/polynote/ui/component/cell.ts#L331-L334

May I suggest perhaps `Shift+F10` like IntelliJ?

**Comment by jeremyrsmith** [comment]
Given that running all cells is something that will typically take multiple minutes, it's pretty important that it be difficult to do by mistake. I think Ctrl+Shift+Enter is too similar Cmd+Shift+Enter which is an existing hotkey (run cell and insert cell below).

I don't think Enter is a good choice for this hotkey, because Enter is otherwise always used when you're in a code cell and you want to do something related to that cell. Run all cells has neither constraint.

**Comment by kuckjwi0928** [comment]
@jonathanindig @jeremyrsmith 
Thanks for the tips!
 I'll do it like IntelliJ `Shift+F10`
