### ISSUE TITLE
Link to a Cell

### ISSUE THREAD

**Issue by devesh** [polynote/polynote#331]
It would be useful to have a way to get a link that can take somebody to a particular cell in a notebook.

**Comment by indig** [comment]
Ooh, I like this idea! thanks! :)

**Comment by jeremyrsmith** [comment]
Hey, while we're at it... it would be neat to be able to link to a particular line in a particular cell and have it highlight like you can do on GitHub/Stash. Or a range of lines even!

**Comment by jeremyrsmith** [comment]
Incidentally, by accident you can already kind of do this with e.g. `#Cell9` at the end of the notebook URL (because each cell's container element has an `id` like that). It just doesn't quite work because we're clobbering the document.location.hash when we do this: https://github.com/polynote/polynote/blob/master/polynote-frontend/polynote/main.js#L271.

Probably tweaking one line of code in the `loadNotebook` method would fix that.

**Comment by indig** [comment]
Resolved by #339
