### ISSUE TITLE
Major refactor: convert to Typescript

### ISSUE THREAD

**Issue by jonathanindig** [polynote/polynote#443]
because types.

**Comment by antonkulaga** [comment]
Why typescript and not ScalaJS? The second looks more reasonable as you have Scala backend code

**Comment by jeremyrsmith** [comment]
@antonkulaga we considered ScalaJS but decided against it for a few reasons.

The main reason I didn't use it from the beginning is this: the main benefit would be sharing ADTs and codecs, but just plainly compiling scodec-based codecs to ScalaJS wouldn't use the fast shared buffer API of ES6 which was pretty important to me (and I wanted to be able to more directly optimize the client-side codecs); also it's just not that much work to write the message types and codecs again in JS with the combinator API we made for it.

When considering the move to typescript, we gave ScalaJS some more thought, but ultimately decided (even optimization concerns aside) that TS was a better fit. I can go into more detail about the thought process if you're curious, but I don't want to come off like I'm bashing ScalaJS because I'm not (I think it's an amazing piece of work). Suffice to say typescript just seems (to us) like a better tool for the job on the front-end; the problems ScalaJS would solve are mainly just avoiding writing certain small pieces twice, but there are drawbacks that we didn't feel were worth it. And we didn't feel that just because Scala has more familiar syntax it would be a better fit; the problem is moreso that web UIs require different architecture choices than backends and so we'd have to learn that anyway (still working on it 😛)
