### ISSUE TITLE
Blank screen on Safari

### ISSUE THREAD

**Issue by nadenf** [polynote/polynote#524]
When opening Polynote for the first time the following Javascript error is shown and the screen is blank:

TypeError: function is not a constructor (evaluating 'super()')

![Screen Shot 2019-10-24 at 5 29 33 pm](https://user-images.githubusercontent.com/657041/67459275-e97ddf80-f683-11e9-838d-29fb7e830cdf.png)

**Comment by jeremyrsmith** [comment]
Welcome! Thanks for the error report!

We haven't tested at all with Safari – we definitely should! Browser support isn't high on the priorities, but we'll run through with Safari and see if it's reasonably simple to solve.

**Comment by ybigus** [comment]
@jeremyrsmith I think, the reason is Safari & IE doesn't support constructors for EventTarget.
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/EventTarget
And [here for an example](https://github.com/polynote/polynote/blob/master/polynote-frontend/polynote/comms.ts#L29), when you're calling super(), BOOM!

**Comment by ybigus** [comment]
I think, adding polyfill can fix this issue:
https://github.com/ungap/event-target
