### ISSUE TITLE
Unable to locate libpython3.so (python support probably won't work)

### ISSUE THREAD

**Issue by aTechGuide** [polynote/polynote#568]
I'm trying to run polynote on MAC OS,
I've used brew to install python on my system

```
brew info python
python: stable 3.7.4 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python/3.7.4_1 (8,567 files, 119.9MB) *
  Built from source on 2019-10-27 at 16:35:42
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb
==> Dependencies
Build: pkg-config ✔
Required: gdbm ✔, openssl@1.1 ✔, readline ✔, sqlite ✔, xz ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Python has been installed as
  /usr/local/bin/python3
```

I tried going through the issues and the suggested steps

`pip3 show jep | grep "^Location:" | cut -d ':' -f 2 | cut -d ' ' -f 2`

Gives
`/usr/local/lib/python3.7/site-packages`

When I run polynote with the following command
```
export POLYNOTE_DEPS=($(ls deps/*.jar))
java -cp polynote.jar:$(IFS=: ; echo "${POLYNOTE_DEPS[*]}") -Djava.library.path=/usr/local/lib/python3.7/site-packages/jep polynote.Main
```

Polynote starts but when I run python code it gives `java.lang.UnsatisfiedLinkError)`

<img width="1372" alt="Screenshot 2019-10-27 at 9 38 19 PM" src="https://user-images.githubusercontent.com/8807997/67637608-3242cc00-f902-11e9-9255-7eebfee5a69e.png">

I tried launching polynote with https://github.com/polynote/polynote/blob/master/scripts/polynote.py script as well 
Command output

```
java -cp polynote.jar:polynote.jar:/Users/bornshrewd/bigdata/polynote/polynote/deps/scala-xml_2.11-1.2.0.jar:/Users/bornshrewd/bigdata/polynote/polynote/deps/scala-library-2.11.11.jar:/Users/bornshrewd/bigdata/polynote/polynote/deps/polynote-runtime.jar:/Users/bornshrewd/bigdata/polynote/polynote/deps/polynote-spark-runtime.jar:/Users/bornshrewd/bigdata/polynote/polynote/deps/scala-collection-compat_2.11-2.1.1.jar:/Users/bornshrewd/bigdata/polynote/polynote/deps/scala-compiler-2.11.11.jar:/Users/bornshrewd/bigdata/polynote/polynote/deps/scala-reflect-2.11.11.jar:/Users/bornshrewd/bigdata/polynote/polynote/deps/portable-scala-reflect_2.11-0.1.0.jar -Djava.library.path=/usr/local/lib/python3.7/site-packages/jep polynote.Main
[INFO]  Loading configuration from config.yml
[zio-default-async-16-1471868639] INFO org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Service bound to address /127.0.0.1:8192
[zio-default-async-16-1471868639] INFO org.http4s.server.blaze.BlazeServerBuilder - 
```

but got `Library not loaded:` Error

<img width="1380" alt="Screenshot 2019-10-27 at 9 42 32 PM" src="https://user-images.githubusercontent.com/8807997/67637659-bb5a0300-f902-11e9-86ae-85d11f478b6c.png">

**Comment by larsleguyt** [comment]
Possibly there is a way to get it working with jep installed through pip aswell (see replies to https://github.com/polynote/polynote/issues/521 for other possible solutions), but I was able to get it to work by [building jep from source](https://github.com/ninia/jep#Installation) on OSX. 
I don't know for sure, but likely this works because the dynamic libraries path is properly set this way? (i.e. for my Homebrew installed Python, the necessary library seems to be at `/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7.dylib`)

1. Clone the jep repository
```git clone git@github.com:ninia/jep.git```

2. Navigate to the directory and install from source
**Note**: jep requires numpy as a dependency, so make sure you install this first if you did not do so yet.
**Note**: if you clone the jep repository to your Polynote app directory, step 3 will likely fail because the `polynote.py` script will find the `jep/` repository directory and set it as the path to jep - you can clone it to any other directory instead.
```cd jep && python setup.py build install```

3. Run Polynote using the [polynote.py](https://github.com/polynote/polynote/blob/master/scripts/polynote.py) script, make sure to move `polynote.py` to your polynote app directory
```python polynote.py```

Besides https://github.com/polynote/polynote/issues/521, I found these related issues:
https://github.com/ninia/jep/issues/182
https://github.com/ninia/jep/issues/113

**Comment by Subarna578** [comment]
I am unable to use python setup.py build install to install jep. It says Please set the environment variable JAVA_HOME to a path containing the JDK. I did everything . I put the JAVA_HOME to my Java sdk-11.0.5 folder but nothing works. Please help...

**Comment by larsleguyt** [comment]
@Subarna578 Are you running this on OSX as well?
Could you post the contents of your JAVA_HOME? Does it have the proper path to the JDK (have you manually checked if it exists, it should be jdk instead of sdk for example)?
```echo $JAVA_HOME```

It [should be able to pickup on it](https://github.com/ninia/jep/blob/master/commands/java.py#L28) if you are manually setting it first using
```export JAVA_HOME=PATH_TO_JDK_HERE```
I think the error you get should only happen if it can't find `JAVA_HOME` in your environment (or the path it is pointing to).

(Btw, if you are also planning to use Spark, the install notes note that  you should use the Java 8 JDK, so it would be good to set your `JAVA_HOME` [to point to that JDK](https://stackoverflow.com/a/52524114) in that case).

**Comment by omerlevran** [comment]
How are you downloading the python3 dependencies? Try running ```python3 -m pip install jep jedi pyspark virtualenv```

**Comment by aTechGuide** [comment]
@larsleguyt  Thanks for your help.
`installing jep from source` works for me. 
Feel free to close this

**Comment by jonathanindig** [comment]
Closing
