### ISSUE TITLE
[ux improvement] ability to switch notebook cell to text within cell drop down

### ISSUE THREAD

**Issue by sshkel** [polynote/polynote#632]
Hi folks,

Firstly, thanks heaps for an amazing tool. I have been using it for the past couple of weeks and the experience has been great. After zeppelin I am rediscovering my love for scala development in notebooks.

Got one suggestion I wanted to fly by you. Should we add "text" option of drop down of a notebook cell. I was trying to use polynote to make a prezo about polynote features, so was mixing text and code quite a bit. Took me a while to realise that I could switch cell type to text at the very top.
 Thoughts?
Happy to try pick that issue up if you think it's not much work for a noob.

**Comment by jeremyrsmith** [comment]
Welcome! Thanks for the suggestion!

I'll say that it was an intentional choice to leave "Text" out of the per-cell menu. The reason is that if you were to switch it to "Text" by accident, the code cell chrome disappears and now you don't have that menu anymore; you'd have to go back to the top to change it back to code. From what we've observed, text cells are actually relatively uncommon, so it seemed more likely that it would cause problems than convenience.

That said, you're not the first to be confused by it. I guess the thing to do would be to make the change and see whether my foreseen usability problem actually affects anyone! 😄

**Comment by jonathanindig** [comment]
Welcome @sshkel  😄 Indeed, you are definitely not the first (see: #422 😉). 

I think the improvement suggested in #437 might also be relevant here (it would also potentially mitigate some of the friction @jeremyrsmith is referencing)

**Comment by sshkel** [comment]
Ahhh, yeah, that's totally fair and it does seem like a better solution. Sorry, for opening a dupe, should've tried searching beforehand. Thanks for clarification!

**Comment by antonkulaga** [comment]
>. The reason is that if you were to switch it to "Text" by accident, the code cell chrome disappears and now you don't have that menu anymore;

Why not just treat text the same way as code and keep code cell chrome?
