### ISSUE TITLE
Add support for JVM args for Scala subprocess-based kernel

### ISSUE THREAD

**Issue by kamilkloch** [polynote/polynote#695]
Data scientists like to have it their way, e.g. `-Xmx50G` ;)

**Comment by jeremyrsmith** [comment]
So, I guess this depends on whether or not you're using Spark. If you *are* using Spark, then you can already set `spark.driver.memory=50g` in the notebook's spark configuration. The trouble is, if you're *not* using Spark then we have no way to configure anything.

If we add some UI to configure this, then it runs the risk of being confusing when you *are* using Spark. So maybe we need to work on explicitly choosing Spark or No Spark, so that we can present the appropriate configuration UI depending on what you select.

**Comment by kamilkloch** [comment]
Fair point. As a manual hack, is it enough to hard-code the desired JVM parameters to the polynote startupt script?

**Comment by jeremyrsmith** [comment]
Well, polynote *does* copy the VM args into the subprocess invocation when using plain-java deployment. So that would work. But the problem is that then the server would also feel entitled to 50G of memory... I don't think it would use more memory as a result, but YMMV 😄 

We'll try to figure out a story around configuring this as it's a pretty glaring omission.

**Comment by kamilkloch** [comment]
Any solution in sight? Configuration option in `config.yml` would suffice :)
