### ISSUE TITLE
editor becomes disabled

### ISSUE THREAD

**Issue by antonkulaga** [polynote/polynote#701]
From time to time (cannot say exact steps to reproduce but it just happens after some time of using multiple notebooks in multiple tabs) all cells in all notebooks becomes not editable (I can put a cursor there, but canot type anything there and only refresh of the page helps).
My browser is Firefox 71.0, OS is Linux Mint 19.1 Tessa

**Comment by jeremyrsmith** [comment]
The cells become non-editable (by design) when you lose connection to the server. If this happens frequently, it would be good to investigate the cause! Is your server running locally or are you connecting to it over the internet?

We should add some more obvious UI indication that you've lost the server connection (it just never seems to happen for us except when restarting the server, so it hasn't gotten much attention)
