### ISSUE TITLE
Not getting Latex output using sympy

### ISSUE THREAD

**Issue by namakshenas** [polynote/polynote#880]
The following piece of code is not returning the output formatted with the Latex display.

```
from sympy import *
init_printing()
x,y,mu = symbols('x,y,\mu')
myfun = -x**(1/2)/y - mu*(exp(x)-y)
```

Trying to display `myfun` in a separate cell:
`In: myfun`
`Out: $\displaystyle - \mu \left(- y + e^{x}\right) - \frac{x^{0.5}}{y}$`

With `print`:
`In: print(myfun)`
`Out: -\mu*(-y + exp(x)) - x**0.5/y`

**Comment by jeremyrsmith** [comment]
@namakshenas does `myfun` have a `_repr_latex_` method?

**Comment by jeremyrsmith** [comment]
I can reproduce. The problem is that `_repr_latex_` includes the delimiters `$` on either side of the generated LaTeX. We feed the LaTeX directly into katex, and it doesn't handle that.

I guess we should strip `$` from either side beforehand? I'm not sure if it's typical for `_repr_latex_` to include the delimiters... but I guess stripping them would likely be harmless in cases where it doesn't.

**Comment by jeremyrsmith** [comment]
According to https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html – the `_repr_latex_` method always includes delimiters. So they must be stripped. It's unclear to me whether, in the notebook file when an output's MIME type is `application/x-latex`, the standard ipynb tools expect the delimiters or not. But I'm going to assume that they should be stripped prior to saving, since they aren't part of the actual LaTeX specified by the MIME type.
