### ISSUE TITLE
tqdm not working 

### ISSUE THREAD

**Issue by amalshaji** [polynote/polynote#947]
**Description**
tqdm progress bar isn't working on the notebook

**Reproduction**
```python
import time
from tqdm import tqdm as t1
from tqdm.notebook import tqdm as t2

# normal tqdm
for _ in t1(range(10)):
      time.sleep(0.1)

# tqdm notebook
for _ in t2(range(10)):
      time.sleep(0.1)
```
both aren't working on the notebook. But the first one is printing out the progress bar on the terminal.

**Screenshots**
1. For normal tqdm,

![t1](https://user-images.githubusercontent.com/18011385/89657245-63691780-d8ea-11ea-8f10-592ec778d1a5.PNG)

The tqdm progress bar is shown in the terminal itself

2. For notebook tqdm

![notebook](https://user-images.githubusercontent.com/18011385/89657346-90b5c580-d8ea-11ea-8b93-fda1bc63c368.PNG)

**Environment**

- Polynote Version: 
   - 0.3.11
- Operating System: 
  - Example: Ubuntu20.04(wsl2)
- JVM Version:
  - Example: 1.8.0_265
- Python Version:
  - Example: 3.7.7
- How you installed Polynote: 
  - Example: I downloaded this release https://github.com/polynote/polynote/releases/download/0.2.12/polynote-dist.tar.gz and then followed [these instructions](https://polynote.org/docs/01-installation.html).

**Comment by jonathanindig** [comment]
Hi @amalshaji thanks for the report. I'm not very familiar with `tqdm` but it looks like it uses IPython/Jupyter widgets for its notebook support, which Polynote is not compatible with. 

However, it looks like by default it prints progress to stderr, which is [not (yet) captured in the notebook](https://github.com/polynote/polynote/issues/431). So, it looks like if you just tell it to print to stdout instead, you should be able to see a progress bar. For example: 
<img width="999" alt="Screen Shot 2020-08-07 at 11 25 20 AM" src="https://user-images.githubusercontent.com/5430417/89676557-b74f0e80-d8a0-11ea-969d-d1c702f46163.png">

Finally, I'm curious - since each cell already provides its own progress information, why do you need `tqdm` in a notebook? Is this being used in a library you are calling from the notebook, for example?

**Comment by amalshaji** [comment]
Thanks for answering. The progress bar is needed to display batch training progress(I'm used to the progress bar thing). Also, some libraries have inbuilt tqdm support.
