### ISSUE TITLE
Polynote Kernel not running, Kernel died unexpectedly

### ISSUE THREAD

**Issue by siddharths067** [polynote/polynote#990]
The notebook contains only a single cell and has these three configurations in `spark-config`
```
spark.driver.userClasspathFirst: true
spark.executor.userClasspathFirst: true
spark.master: local[*]
```

And there is only one cell
```
val scalaDF = spark.createDataFrame(List((8, "bat"),
(64, "mouse"),
(-27, "horse")))
```

However, when I try to run this cell the kernel returns this error in the logs
```
[ERROR]   (Logged from NotebookSession.scala:174)
   |     polynote.kernel.remote.SocketTransport$ProcessDied$: Kernel died unexpectedly
   |     polynote.kernel.remote.SocketTransport$ProcessDied$.<clinit>(transport.scala)
   |     polynote.kernel.remote.SocketTransport$$anonfun$polynote$kernel$remote$SocketTransport$$monitorProcess$1$$anonfun$apply$42.apply(transport.scala:244)
   |     polynote.kernel.remote.SocketTransport$$anonfun$polynote$kernel$remote$SocketTransport$$monitorProcess$1$$anonfun$apply$42.apply(transport.scala:244)
   |     zio.ZIO$$anonfun$fail$1.apply(ZIO.scala:2300)
   |     zio.ZIO$$anonfun$fail$1.apply(ZIO.scala:2300)
   |     zio.internal.FiberContext.evaluateNow(FiberContext.scala:391)
   |     zio.internal.FiberContext.zio$internal$FiberContext$$run$body$2(FiberContext.scala:687)
   |     zio.internal.FiberContext$$anonfun$12.run(FiberContext.scala:687)
   |     java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   |     java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
   |     java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by jonathanindig** [comment]
How are you running Polynote? Do you have spark installed on your machine? Does `spark-submit` work? 

If you don't have Spark installed on your machine, you either need to install it, or set your Kernel Isolation setting so that Polynote creates a Spark session inside the server process. Set the following in your `config.yml` (you'll need to create that file if you don't have one already, put it in the directory you are running Polynote from):

```
behavior:
  kernel_isolation: never
```

Note that this will cause your notebooks to share the same Spark session (a Spark limitation, as there can only be a single Spark Session per process), so it's possible you will encounter strange behavior or incomplete isolation if you run multiple Spark notebooks at the same time.

**Comment by jonathanindig** [comment]
Hi @siddharths067, I hope you were able to resolve this problem. I'm going to close this issue for now, but if you still need help please feel free to comment with the information I requested above. Thanks!
